/**
 * DOM rendering helpers for analysis results.
 */

function escapeHtml(t) {
  const d = document.createElement('div');
  d.textContent = t;
  return d.innerHTML;
}

function strengthColor(score) {
  if (score >= 70) return 'var(--green)';
  if (score >= 45) return 'var(--yellow)';
  return 'var(--orange)';
}

export function renderResults(data) {
  const color = strengthColor(data.strength);

  return `
    <div class="results-grid">
      <div class="glass-card strength-card animate__animated animate__fadeInUp">
        <p class="gauge-label">Case Strength</p>
        <div class="gauge-bar">
          <div class="gauge-fill" style="width: ${data.strength}%; background: ${color};"></div>
        </div>
        <p class="gauge-score" style="color: ${color};">${data.strength}% &mdash; ${data.strengthLabel}</p>
      </div>

      <div class="glass-card animate__animated animate__fadeInUp" style="animation-delay: 0.1s;">
        <p class="section-label">Key Legal Issues</p>
        <ul class="issues-list">
          ${data.issues.map((i) => `<li>${escapeHtml(i)}</li>`).join('')}
        </ul>
      </div>

      <div class="glass-card animate__animated animate__fadeInUp" style="animation-delay: 0.2s;">
        <p class="section-label">Relevant Areas of Law</p>
        <div class="tag-list">
          ${data.areas.map((a) => `<span class="tag">${escapeHtml(a)}</span>`).join('')}
        </div>
      </div>

      <div class="glass-card animate__animated animate__fadeInUp" style="animation-delay: 0.3s;">
        <p class="section-label">Recommended Next Steps</p>
        <ol class="steps-list">
          ${data.steps.map((s) => `<li>${escapeHtml(s)}</li>`).join('')}
        </ol>
      </div>

      <div class="disclaimer animate__animated animate__fadeIn" style="animation-delay: 0.5s;">
        <p>This analysis is generated by AI for informational purposes only. It does not constitute legal advice. Always consult a qualified attorney for guidance on your specific situation.</p>
      </div>

      <div style="text-align: center; margin-top: 0.5rem; animation-delay: 0.6s;" class="animate__animated animate__fadeIn">
        <button class="btn-secondary" id="reset-btn">Analyze Another Case</button>
      </div>
    </div>
  `;
}

export function renderLoading() {
  return `
    <div class="loading">
      <div class="spinner"></div>
      <p style="color: var(--text-muted); font-size: 0.9rem;">Analyzing your case...</p>
    </div>
  `;
}
