#!/usr/bin/env bash
set -euo pipefail

TARGET_DIR="${1:-.}"
TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"
PROJECT_NAME="$(basename "$TARGET_DIR")"

cd "$TARGET_DIR"

STACK=()
[[ -f package.json ]] && STACK+=("Node.js")
[[ -f pyproject.toml || -f requirements.txt ]] && STACK+=("Python")
[[ -f go.mod ]] && STACK+=("Go")
[[ -f Cargo.toml ]] && STACK+=("Rust")
[[ ${#STACK[@]} -eq 0 ]] && STACK+=("Unknown")

if [[ ! -f README.md ]]; then
  cat > README.md <<EOF
# ${PROJECT_NAME}

Auto-generated baseline README.
EOF
fi

if ! rg -q "^## Quick Commands" README.md; then
  cat >> README.md <<'EOF'

## Quick Commands
- `./scripts/simplify.sh` - organize project files into clean folders
- `./scripts/monetize.sh . --write` - generate monetization plan
- `./scripts/audit.sh .` - run a fast project audit
- `./scripts/ship.sh .` - run checks and ship changes
EOF
fi

cat > DOCS.md <<EOF
# ${PROJECT_NAME} Docs Snapshot

## Stack
- $(IFS=", "; echo "${STACK[*]}")

## Project Tree (Top Level)
\`\`\`
$(find . -maxdepth 2 -mindepth 1 -not -path "*/.git/*" | sed 's#^\./##' | sort)
\`\`\`

## Notes
- Generated by ./scripts/docs.sh on $(date +"%Y-%m-%d %H:%M:%S")
EOF

echo "Updated README.md and wrote DOCS.md"

